config/routes.rb
Rails.application.routes.draw do
  root to: 'tops#index'
  post "likes/:beach_id/create" => "likes#create"
  post "likes/:beach_id/destroy" => "likes#destroy"
  resources :likes, only: [:show, :create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :beaches do
   collection do
      get :top5
   end
  end 
  resource :beaches, only: [:like] do
    collection do
      post :confirm
      get :like
    end
  end 
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/beach.rb
class Beach < ApplicationRecord
  validates :name, presence: true
  validates :image, presence: true
  validates :information, presence: true, length: { maximum: 300 }
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :like_users, through: :likes, source: :user
  mount_uploader :image, ImageUploader
  paginates_per 10
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :beach 
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :email, uniqueness: true
  before_save { email.downcase! }
  has_secure_password # パスワードのハッシュ化（登録フォームの作成)
  validates :password, presence: true, length: { minimum: 6 }
  has_many :beaches, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_beaches, through: :likes, source: :beach
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  
  before_action :set_search

  def set_search
    @q = Beach.ransack(params[:q]) 
    @result = @q.result.page(params[:page]).per(5).order('created_at DESC') 
  end
  
  def after_sign_in_path_for(resource) 
　　beaches_path
  end
end

app/controllers/beaches_controller.rb
class BeachesController < ApplicationController
  before_action :set_beach, only: [:show, :edit, :update, :destroy]
  before_action :logged_in?, only: [:new, :show, :edit]
  
  def index
    @beaches = Beach.order(:created_at).reverse_order
    @beaches = Beach.page(params[:page]).per(6).order('created_at DESC')
    @q = Beach.ransack(params[:q]) 
    @result = @q.result.page(params[:page]).per(6).order('created_at DESC') 
    
  end
  
  def new
    if params[:back]
      @beach = current_user.beaches.new(beach_params)
    else
      @beach = current_user.beaches.new
    end  
  end 
  
  def create
    @beach = Beach.new(beach_params)
    @beach.user_id = current_user.id
    @beach.image.retrieve_from_cache! params[:cache][:image] if params[:cache][:image].present?
      if @beach.save
        redirect_to beaches_path, notice:"post completed!"
      else
       render 'new'
      end
  end 
  
  def show
    @like = current_user.likes.find_by(beach_id: @beach.id)
    @likes_count = Like.where(beach_id: @beach.id).count
  end
  
  def top5
    @top5 = Beach.find(Like.group(:beach_id).order('count(beach_id) desc').limit(5).pluck(:beach_id))
  end
  
  def edit
  end
  
  def update
    if @beach.update(beach_params)
      redirect_to beaches_path, notice: "post edited!"
    else
      render 'edit'
    end  
  end  
  
  def destroy
    @beach.destroy
    redirect_to beaches_path, notice:"post deleteed!"
  end  
  
  def like
    @like = current_user.likes.find_by(beach_id: params[:beach_id])
  end 
 
  def confirm
    @beach = current_user.beaches.new(beach_params)
    render :new if @beach.invalid?
  end  
  
  private
  def beach_params
    if params[:beach]
      params.require(:beach).permit(:name, :address, :information, :image)
    else false
    end
  end
  
  def set_beach
    @beach = Beach.find_by_id(params[:id])
  end  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.create(beach_id: params[:beach_id])
    redirect_to beaches_url, notice: "#{@like.beach.user.name}さんのBeachをいいね！しました"
  end
 
  def show
    @user = User.find(params[:id])
    @like_beaches = @user.like_beaches
  end

  def destroy
    like = current_user.likes.find_by(beach_id: params[:beach_id]).destroy
    redirect_to beaches_url, notice: "#{like.beach.user.name}さんのいいね！を解除しました"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to beaches_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render 'new'
    end 
  end
  
  def destroy
    session.delete(:user_id) #現在のユーザーをnilに設定で
    flash[:notice] = "ログアウトしました"
    redirect_to new_session_path
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
    def index
    end    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
       BeachMailer.beach_mail(@user).deliver
      redirect_to user_path(@user.id) 
      else
      render 'new'
    end  
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def simple_time(time)
    time.strftime("%Y-%m-%d　%H:%M　")
  end

end

app/helpers/beaches_helper.rb
module BeachesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_beaches_path
    elsif action_name == 'edit'
      beach_path
    end
  end 
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
   def current_user
    @current_user ||= User.find_by(id: session[:user_id])
   end
    
   def logged_in?
      !current_user.nil? 
   end 
    
   def request_login
      if current_user.nil?
        redirect_to new_session_path, notice: "ログインが必要です"
      end
   end  
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/beaches/_form.html.erb
<div class="container">
  <div class="contents">

<body class="background">
<%= form_with(model: @beach, local: true, url: choose_new_or_edit) do |form| %>
<% if @beach.errors.any? %>
    <div id="error_explanation">
      <h3 class="error_msg_form"><%= @beach.errors.count %>件のエラーがあります。</h3>
      <ul>

      <% @beach.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="beach_name">
    <%= form.label :name, id: :form_label %>
  </div>
  <div>
    <%= form.text_field :name, id: :new_form, :size=>"30", :placeholder => " ラニカイビーチ, Lanikai beach, etc...  " %>
  </div>
  <div class="beach_name">
    <%= form.label :address, id: :form_label %>
  </div>
  <div>
    <%= form.text_field :address, id: :new_form, :size=>"30", :placeholder => " ハワイ, Hawaii, etc...  " %>
  </div>
  
  <div class="field">
  <%= form.label :image, id: :form_label %>
  </div>
  <div>
  <%= form.file_field :image, id: :beach_image %>
  <%= form.hidden_field :image_cache %> 
  </div>
  
  <div class="beach_name">
    <%= form.label :information, id: :form_label %>
  </div>
  <div>
    <%= form.text_area :information, id: :information_form, :size => "40x5", :placeholder => "天国に一番近い島。。。  "  %>
  </div>
  <%= form.submit "create", :class=>"btn btn-primary btn-sm", id: :form_btn%>
<% end %> 
</body>

   
  </div>
</div>

app/views/beaches/confirm.html.erb
<div class="container">
  <div class="contents">
    <div class="article">
<h4>以下の内容で送信</h4>
<br>

<%= form_with(model: @beach, url: beaches_path, local: true) do |form| %>
  <%= form.hidden_field :name %> 
  <%= form.hidden_field :address %>
  <%= form.hidden_field :image %>
  <%= form.hidden_field :information %>

<div>
<%= image_tag(@beach.image.url) %>
<%= hidden_field_tag :"cache[image]",@beach.image.cache_name%>
<%= form.hidden_field :id %>
</div>

<p><strong>Name: </strong><%= @beach.name%></p>
<p><strong>Address: </strong><%= @beach.address%></p> 

<div class="row">
<div><strong>Information</strong></div>
<div class="col-xs-12 col-sm-12 col-md-4"></div><!--ダミーcol--!>
<div class="col-xs-12 col-sm-12 col-md-4"><p class="information"><%= @beach.information%></div>
<div class="col-xs-12 col-sm-12 col-md-4"></div><!--ダミーcol--!>
</div>

</div><!--article締め--!>
<div id="submit_btn">
<%= form.submit "Submit Post", :class=>"btn btn-primary btn-sm"%>
</div>
<% end %>

<%= form_with(model: @beach, url: new_beach_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :name %> 
  <%= form.hidden_field :address %>
  <%= form.hidden_field :image %>
  <%= form.hidden_field :information %>
  
  <%= form.submit "Go Back to Previous Page", name: 'back', :class=>"btn btn-primary btn-sm" %>
<% end %>

 </div>
</div>

app/views/beaches/edit.html.erb
<div class="article">
<h3 class="edit">Edit page</h3>

<%= render 'form' %>
</div>

app/views/beaches/index.html.erb
<div class="container">
  <div class="contents">
    
  <h5 class="index_p1">世界中に色々なビーチがありますが、実際どこがおすすめですか？</h5><br>
  <h5 class="index_p1">国内、海外の素敵なビーチを投稿したり、探すことができるアプリです。</h5>
<br>
<h4>投稿されてるお薦めビーチ</h4>

 <div class="row">
  <% @result.each do |beach| %>
      <div class="beach-index col-xs-12 col-sm-12 col-md-4"><%= link_to image_tag(beach.image), beach_path(beach.id), class: "image"  %>
        <p><strong>Name: </strong><%= beach.name%></p>
        <p><strong>Address: </strong><%= beach.address%></p>
      </div><!--col締め--!>
  <% end %>
 </div>
 
    <div>
    <%= paginate @beaches %>
    </div>
    <br>
    <div>
    <a class="btn btn-primary btn-sm" href="beaches/new" role="button">Back to Post</a>
    </div>
    
  </div>
</div>

app/views/beaches/new.html.erb
<div class="article">
<h3 class="new_post">Post recommend beach</h3>

<%= render 'form' %>

</div>

app/views/beaches/show.html.erb
<div class="container">
  <div class="contents">
      <div class="article">
        
    　<h4><%= @beach.user.name %>さんのpost</h4> 
  
<div class="row">
   <div class="col-xs-12 col-sm-12 col-md-2"></div>
   <div class="img-show col-xs-12 col-sm-12 col-md-4"><%= image_tag(@beach.image_url)%></div>
   
   <div class="explanation-show col-xs-12 col-sm-12 col-md-4">
   <p><strong>Name: </strong><%= @beach.name%></p>
   <p><strong>Address: </strong><%= @beach.address%></p> 
   <p class="information"><%= @beach.information%></p> 
   <p>date: <%= simple_time(@beach.created_at) %></p>
 
 <% unless @beach.user == current_user %>
    <% if @like.present? %>
      <%= link_to("/likes/#{@beach.id}/destroy", {method: "post"}) do %>
      <span class="fa fa-heart fa-unlikebtn fa-2x"></span>
      <% end %>
    <% else %>
      <%= link_to("/likes/#{@beach.id}/create", {method: "post"}) do %>
      <span class="fa fa-heart-o fa-likebtn fa-2x"></span>
      <% end %>
    <% end %>
      <br>
      <!-- 変数@likes_count表示 -->
      <%= @likes_count %> likes
  
 <% end %>

    <% if @beach.user_id == current_user.id %>
      <div class="edit_delete_btn">   
      <%= link_to 'Edit', edit_beach_path(@beach.id) %> | 
      <%= link_to 'Delete', beach_path(@beach.id), method: :delete, data: { confirm: '本当に削除していいですか？'} %>
      </div>
    <% end %>
   
    </div>  
  
   <div class="col-xs-12 col-sm-12 col-md-2"></div>
    </div>

      </div>
    
     <div id="back_to_list">
     <%= link_to 'Back to List', beaches_path, class: 'btn btn-primary btn-sm' %>
     </div>
     
 </div>
</div>

app/views/beaches/top5.html.erb
<div class="container">
  <div class="contents">
    <div class="article">
      
    <h3>Beach Ranking Top5</h3>
    <br>

<div class="row">
<% @top5.each.with_index(1) do |f, i|%>
<div class="ranking_fram">
  <h2 class="ranking_label"><span class="label label-danger"><%= "No.#{i}" %></span></h2>
  <div><%= link_to image_tag(f.image), beach_path(f.id), class: "image" %></div>
  <div><strong>Beach name</strong></div>
  <div><%= f.name %></div>
  <div><strong>Beach address</strong></div>
  <div><%= f.address %></div>
  <div>Post date: <%= simple_time(f.created_at) %></div>
  <span class="fa fa-heart-o fa-likebtn fa-2x"></span><p><%= f.like_users.count %> likes</p> 
</div>   
       
<% end %>
</div>

    <div>
     <%= link_to 'Back to List', beaches_path, class: 'btn btn-primary btn-sm' %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BestBeaches</title>
    <%= csrf_meta_tags %>
　　<meta name="viewport" content="width=device-width"> <!--モバイルブラウザ用--!>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <!-- Optional theme -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css">
    <!-- Latest compiled and minified JavaScript -->
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    
  </head>
  <body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/"><i class="fa fa-anchor "></i></a>
      </div>
      <div id="gnavi" class="collapse navbar-collapse navbar-right">
        <ul class="nav navbar-nav">
          <% if logged_in? %>
            <!--検索機能--!>
            <div class="form-group navbar-form navbar-left">
             <%= search_form_for @q do |f| %>  
              <!-- orで複数フィールドを指定できる --!>
              <%= f.search_field :name_or_address_cont, :placeholder => "Beach name or Address", :size => "18px", :class => "form-control" %>
              <%= button_tag :type => "submit", :class =>"btn btn-default btn-s-md" do %><i class="fa fa-search"></i>
              <% end %>
              <%= link_to 'clear', url_for, class: "btn btn-primary btn-sm" %>
             <% end %>
            </div>
              <li><%= link_to "Post", new_beach_path %></li>
              <li><%= link_to "List", beaches_path %></li>
              <li><%= link_to "Like", like_path(current_user.id) %></li>
              <li><%= link_to "Beach ranking", top5_beaches_path %></li>
              <li><%= link_to "Log out", session_path(current_user.id), method: :delete %></li>
            <div id="gnavi" class="collapse navbar-collapse navbar-right">
          <% else %>
            <li class="sign"><%= link_to "log in", new_session_path %></li>
            <li class="sign"><%= link_to "sign up", new_user_path %></li>
            
          <% end %>          
        </ul>
      </div>
    </div>
  </nav> 
  <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <%= yield %>
    </body>
    <footer>
     © 2018 Best Beaches 
  　</footer>
  
</html>

app/views/likes/show.html.erb
<div class="container">
  <div class="contents">
    <div class="article">
    <h3>あなたのLikeしたPage</h3>
    <p>画像をクリックすると詳細を確認できます。</p>
 
<% if @like_beaches.present? %>   
 <div class="row">
   <% @like_beaches.each do |t| %>
      <div class="beach-index col-xs-12 col-sm-12 col-md-4"><%= link_to image_tag(t.image), beach_path(t.id), class: "image"  %>
      <p><strong>Name: </strong><%= t.user.name %></p>
      <p><strong>Address: </strong><%= t.address %></p>
        
        <%= link_to("/likes/#{t.id}/destroy", {method: "post"}) do %>
        <span class="fa fa-heart fa-unlikebtn fa-2x"></span>
        <% end %>  
      </div><!--col締め--!>
      
   <% end %>
<% end %> 
 </div><!--row締め--!>
   </div><!--article締め--!> 
 
    <div>
     <%= link_to 'Back to List', beaches_path, class: 'btn btn-primary btn-sm' %>
    </div>
    
  </div>
</div>

app/views/tops/index.html.erb
<div class="container">
  <div class="contents_top">
    
<body class="background">
    
<div class="loading">
  <span data-text="F">F</span>
  <span data-text="a">a</span>
  <span data-text="v">v</span>
  <span data-text="o">o</span>
  <span data-text="r">r</span>
  <span data-text="i">i</span>
  <span data-text="t">t</span>
  <span data-text="e">e</span>
  <span data-text="B">B</span>
  <span data-text="e">e</span>
  <span data-text="a">a</span>
  <span data-text="c">c</span>
  <span data-text="h">h</span>
  <span data-text="e">e</span>
  <span data-text="s">s</span>
</div>

<p class="topindex_p1">国内、海外の素敵なビーチ　あなたはどこでどんなことしてみたい？<br>
お気に入りのビーチを紹介するアプリです。</p>

</body>
    
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="contents_top">

<body class="background">
<h3 class="signup_form">Create your account</h3>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
<div class="signup_form">
  <%= f.text_field :name, id: :form, :size=>"30", :placeholder => "  name" %>
</div>
<div class="signup_form">
  <%= f.email_field :email, id: :form, :size=>"30", :placeholder => "  email address" %>
</div>
<div class="signup_form">
  <%= f.password_field :password, id: :form, :size=>"30", :placeholder => "  password" %>
</div> 
<div class="signup_form"> 
  <%= f.password_field :password_confirmation, id: :form, :size=>"30",  :placeholder => "  password confirmation" %>
</div>

<div class="signup_form_btn">
  <%= f.submit "Sign in", :class=>"btn btn-primary btn-sm" %>
</div>

<% end %>

</body>

  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="contents_top">

<body class="background">
<h4>Success to Sing up</h4>

<h3><span class="title"><%= @user.name %></span>さん</h3>

<p>登録メールアドレス<br><%= @user.email %></p>

<p>アプリをご利用の際は<a href="/sessions/new">Log in</a>が必要です。</p>
<p>Please <a href="/sessions/new">Log in</a> to open the app</p>

<p id="notice"><%= notice %></p>

</body>

  </div>
</div>